---
# HTPasswd secret - contains hashed passwords
# Default: admin / d3v3l0p3rs
apiVersion: v1
kind: Secret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
type: Opaque
data:
  htpasswd: YWRtaW46JDJ5JDA1JHM3UDlpcktocHlSOUtXNFpIeDBCMmU0RTA2Mk5oMGtqTzRTVkV5L2U0c0xrNzV6a1Roc0VXCg==
