apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: orchestrator-operators
  annotations:
    config.openshift.io/description: "OpenShift Serverless and Serverless Logic operators for RHDH Orchestrator"

resources:
- serverless-operator.yaml
- serverless-logic-operator.yaml
- orchestrator-operator.yaml
