apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    dev.azure.com/project-repo: ${{ values.project }}/${{ values.name }}
    dev.azure.com/build-definition: ${{ values.name }}-ci
    backstage.io/kubernetes-id: ${{ values.name }}
    backstage.io/kubernetes-namespace: ${{ values.namespace }}
  tags:
    - nodejs
    - typescript
    - azure-devops
  links:
    - url: https://dev.azure.com/${{ values.organization }}/${{ values.project }}/_git/${{ values.name }}
      title: Azure DevOps Repo
      icon: source
    - url: https://devspaces.apps.CLUSTER_DOMAIN_PLACEHOLDER/f?url=https://dev.azure.com/${{ values.organization }}/${{ values.project }}/_git/${{ values.name }}
      title: Open in Dev Spaces
      icon: cloud
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner | default("user:default/admin", true) }}
